Add form field to stories
FlowFuse/website pull request #1478
Opened 2024-01-08 17:14 UTC by Yndira-FlowForge

## Description

I've added the form field to the template and each story so users can download the PDF version.

## Related Issue(s)

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

2024-01-08 17:24 UTC, Yndira-FlowForge commented on src/_includes/layouts/story.njk
> +                            <h3 class="mb-3">Download webinar slides</h3>
```suggestion
                            <h3 class="mb-3">Download customer story</h3>
```

2024-01-08 18:54 UTC, Yndira-FlowForge commented
@Hasmin-AC, I initially planned to address [this](https://flowforgeworkspace.slack.com/archives/C02TG4WH5PC/p1704701959127949?thread_ts=1704255341.202729&cid=C02TG4WH5PC) through a separate PR. However, I realized its connection to this one. Perhaps we can collaborate on creating instructions for adding a new customer story, including guidance on creating the form in HubSpot? I'll need your help with that part.

2024-01-08 19:44 UTC, Hasmin-AC commented on src/customer-stories/leveraging-node-red-and-flowfuse-to-revolutionize-irrigation.md
> +    formId: 1b361db7-cf8e-4574-981b-9de01de04fd9
```suggestion
    formId: f77ee5dd-6e7a-4475-aa66-4f1824aab8d7
```

2024-01-08 19:48 UTC, Hasmin-AC commented on src/customer-stories/opto22-embraces-node-red.md
> +    formId:
```suggestion
    formId: ef2e9c57-df05-456e-a612-0531c3241002
```

2024-01-08 19:51 UTC, Hasmin-AC commented on src/customer-stories/stfi-future-of-textile-powered-by-node-red.md
> +    formId:
```suggestion
    formId: 04a5843c-1d39-4410-8727-af15b42108d1
```

2024-01-08 19:53 UTC, Hasmin-AC commented on src/customer-stories/un-wmo-nr-data-sharing.md
> +    formId:
```suggestion
    formId: 37f86f46-62d1-4203-bce9-0318ce993710
```

2024-01-08 19:57 UTC, Hasmin-AC requested changes
updated the form IDs

2024-01-09 10:59 UTC, Yndira-FlowForge commented on src/_includes/layouts/story.njk
> +                            <h3 class="mb-3">Download customer story</h3>
```suggestion
                            <h3 class="mb-3">Download Case Study</h3>
```

2024-01-09 13:14 UTC, ZJvandeWeg approved these changes

2024-01-09 16:24 UTC, Hasmin-AC approved these changes

2024-01-09 16:24 UTC, merged