Abasive Tech Customer Story
FlowFuse/website pull request #1679
Opened 2024-02-20 08:51 UTC by robmarcer

2024-02-23 17:46 UTC, gdziuba approved these changes
Looks great.  Great reference.

2024-02-23 17:47 UTC, gdziuba commented
@Hasmin-AC @robmarcer

Do we have a time for when we want to promote?

2024-02-26 11:56 UTC, ZJvandeWeg requested changes

2024-02-26 11:56 UTC, ZJvandeWeg commented on src/customer-stories/leveraging-node-red-and-flowfuse-to-automate-precision-manufacturing.md
> +This case study provides an in-depth exploration of how Abrasive Technology harnessed the power and flexibility of Node-RED to optimize automation, streamline communication with machinery, and accele
```suggestion
This case study provides an in-depth exploration of how Abrasive Technology harnessed the power and flexibility of FlowFuse and Node-RED to optimize automation, streamline communication with machinery, and accelerate development processes.
```

2024-02-26 11:56 UTC, ZJvandeWeg commented on src/customer-stories/leveraging-node-red-and-flowfuse-to-automate-precision-manufacturing.md
> +Abrasive Technology initially utilized Raspberry Pis for hosting Node-RED instances, linking them to industrialized touch screens for Human-Machine Interfaces (HMIs). While Raspberry Pis proved relia
```suggestion
Abrasive Technology initially utilized Raspberry Pis for hosting Node-RED instances, linking them to industrialized touch screens for Human-Machine Interfaces (HMIs). While Raspberry Pis proved reliable for many applications, certain projects pushed hardware capabilities. Dudley highlights: "I have found them to be very reliable, but on the current project, I'm absolutely bumping up against its hardware capabilities." The anticipation of the Pi5, with enhanced capabilities, holds promise, and Dudley is eagerly awaiting its arrival.
```

2024-02-26 11:56 UTC, ZJvandeWeg commented on src/customer-stories/leveraging-node-red-and-flowfuse-to-automate-precision-manufacturing.md
> +In addition to Raspberry Pis, Abrasive Technology currently operates a server running Node-RED locally, with additional instances in locally installed FlowFuse. Dudley notes, “We are now actively tra
```suggestion
In addition to Raspberry Pis, Abrasive Technology currently operates a server running Node-RED locally, with additional instances in locally installed FlowFuse. Dudley notes, “We are now actively transitioning our Node-RED instances from locally maintained servers to the FlowFuse Cloud.”
```

2024-02-26 19:57 UTC, Hasmin-AC commented
In the summary can we add a line or two on how FlowFuse helped too.

2024-02-28 11:43 UTC, ZJvandeWeg commented
@robmarcer Yes, last question from my side is if you updated the PDF for download too?

2024-02-28 11:44 UTC, ZJvandeWeg approved these changes

2024-02-28 11:44 UTC, merged

2024-02-28 13:16 UTC, robmarcer commented
I've updated the PDF @ZJvandeWeg, thanks for the reminder.