Update our default blog post image
FlowFuse/website pull request #1798
Opened 2024-03-15 14:51 UTC by Yndira-E

## Description

I've removed the script that automatically generated the tile images when none were set and replaced it with an image that better aligns with our new colour scheme and style.

## Related Issue(s)

closes [#1793](https://github.com/FlowFuse/website/issues/1793)

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

2024-03-15 15:26 UTC, Yndira-E commented
Hi @knolleary,
I've commented out the images in some files—the ones that used to require the auto-generated image. This was done to check if it worked and to see how they looked in context. I thought it could be useful to maintain them this way for the review. Could you please take a look as is? I'll uncomment those images afterward.

2024-03-18 10:15 UTC, ZJvandeWeg commented on src/blog/2024/03/flowfuse-self-hosted-starter-resource-limits.md
This is the example I take it?

2024-03-18 10:21 UTC, Yndira-E commented
@ZJvandeWeg yes, that's one of them. Here's a list:
https://deploy-preview-1798--flowforge-website.netlify.app/blog/
https://deploy-preview-1798--flowforge-website.netlify.app/blog/2024/03/flowfuse-self-hosted-starter-resource-limits/
https://deploy-preview-1798--flowforge-website.netlify.app/webinars/ (different default images for the next and past webinars)
https://deploy-preview-1798--flowforge-website.netlify.app/customer-stories/

2024-03-18 11:24 UTC, ZJvandeWeg requested changes

2024-03-18 11:24 UTC, ZJvandeWeg commented on src/community/newsletter.njk
> +                        <div class="w-full h-auto mb-10">
Can we make this a partial or shortcode? Not sure what's more appropriate on a tehcnical level, but feels like if we DRY our code, it's easier going forward

Ref: https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

2024-03-18 11:59 UTC, knolleary commented
Looks good - but will echo ZJ's comment on whether we can now pull that common piece that inserts the right image into a single place that can be reused.

2024-03-18 13:36 UTC, Yndira-E commented
I have created a shortcode that works for most of the templates. However, the templates involving customer-stories are not exactly the same across all files. The exceptions are /node-red and /landing/cloud-signup/. The latter is temporary, so I decided not to create a partial for it, as it will eventually be unnecessary. However, I'm open to feedback if we think it's needed.

I've left the image paths commented out for now so you can verify that everything is working correctly. Please let me know if everything looks good on your end, and I'll proceed to uncomment the image paths.

2024-03-19 09:24 UTC, knolleary approved these changes
Looks good to me

2024-03-19 09:30 UTC, ZJvandeWeg approved these changes

2024-03-19 10:24 UTC, Yndira-E commented on src/blog/2024/03/looking-towards-node-red-4.md
> +image: #/blog/2024/03/images/looking-towards-node-red-4.png
```suggestion
image: /blog/2024/03/images/looking-towards-node-red-4.png
```

2024-03-19 10:24 UTC, Yndira-E commented on src/blog/2024/03/flowfuse-self-hosted-starter-resource-limits.md
> +image: #/blog/2024/03/images/starter-tier-resource-limits.png
```suggestion
image: /blog/2024/03/images/starter-tier-resource-limits.png
```

2024-03-19 10:24 UTC, Yndira-E commented on src/customer-stories/un-wmo-nr-data-sharing.md
> +image: #/images/stories/un-wmo.jpg
```suggestion
image: /images/stories/un-wmo.jpg
```

2024-03-19 10:24 UTC, Yndira-E commented on src/webinars/2024/balena.md
> +image: #/images/webinars/enterprise-grade-edge-device-fleet-management-balena-and-flowfuse-webinar-january-2024.jpg
```suggestion
image: /images/webinars/enterprise-grade-edge-device-fleet-management-balena-and-flowfuse-webinar-january-2024.jpg
```

2024-03-19 10:24 UTC, Yndira-E commented on src/webinars/2024/building-unified-namespace-using-nodered-mqtt.md
> +image: #/images/webinars/building-unified-namespace-uns-using-node-red-and-mqtt-webinar-2024-march.jpg
```suggestion
image: /images/webinars/building-unified-namespace-uns-using-node-red-and-mqtt-webinar-2024-march.jpg
```

2024-03-19 10:24 UTC, Yndira-E commented on src/customer-stories/leveraging-node-red-and-flowfuse-to-revolutionize-irrigation.md
> +image: #/images/stories/pidd-view.png
```suggestion
image: /images/stories/pidd-view.png
```

2024-03-19 11:08 UTC, merged