doc: Add instructions for utilizing the pre-staging environment
FlowFuse/website pull request #1837
Opened 2024-03-25 09:54 UTC by ppawlowski

## Description

This Pull Request extends development documentation by adding information about the possibility of validating changes before emerging to the `main` branch.

## Related Issue(s)

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

2024-03-27 09:38 UTC, joepavitt commented
Why can't we do this for _every_ PR - why does it need the manual step of adding a label?

2024-03-27 09:46 UTC, knolleary commented
@joepavitt because so far we choose not to.

I believe that for many PRs the test env would go untouched because the PR has been tested locally and the nature of the change doesn't require a dedicated env for further manual testing. We would be throwing money at AWS for no value in return.

If we decided it was worthwhile spinning up on every PR we could do so. I don't think that's necessary today.

2024-03-27 09:46 UTC, hardillb commented
@joepavitt because not every change needs a K8s environment to test it

2024-03-27 09:47 UTC, ppawlowski commented
@joepavitt  AFAIR this was the main expectation - to have a possibility to verify changes which may break the staging environment.  Not all of them will tend to do this and can be merged and deployed to staging without validation on the pre-staging environment. 
@ZJvandeWeg as it is mentioned in the docs, `This environment is terminated upon PR merging or closure.`

2024-03-27 09:48 UTC, ppawlowski commented
To be more clear - from the infrastructure perspective, an environment is in fact FlowFuse Cloud instance running on an existing EKS cluster we use for the staging environment. No new AWS resources are created.

2024-03-27 10:39 UTC, joepavitt commented
Can we just sanity check one thing, fairly sure it's covered by the `synchronise` event, but if the base `main` branch is updated, would we auto-deploy the relevant changes to any open PRs?

Thinking of a situation where we have _potentially_ clashing PRs. When one is merged (having been verified in staging) that would update `main`, an associated PR should have it's staging environment also updated to reflect the latest `main`.

2024-03-27 12:00 UTC, joepavitt commented
Let's get 1. and 2. ticked of please @ppawlowski

2024-03-28 11:22 UTC, joepavitt requested changes

2024-03-28 11:22 UTC, joepavitt commented on src/handbook/development/contributing.md
> +To validate changes within the pre-staging environment, apply the deploy:pr label to the PR. The PR will then undergo automatic deployment to the pre-staging environment, and the deployment link will
```suggestion
To validate changes within the pre-staging environment, apply the `deploy:pr` label to the PR. The PR will then undergo automatic deployment to the pre-staging environment, and the deployment link will be appended to the associated workflow summary. The label should remain until the PR is merged.
```

2024-03-28 11:22 UTC, joepavitt commented on src/handbook/development/contributing.md
> +To validate changes within the pre-staging environment, apply the deploy:pr label to the PR. The PR will then undergo automatic deployment to the pre-staging environment, and the deployment link will
Can we also get a bit more detail on where to find the link (maybe a screenshot) - given these instructions, and [this example PR](https://github.com/FlowFuse/flowfuse/pull/3652#discussion_r1542676749) - I cannot find the link

2024-03-28 12:11 UTC, joepavitt approved these changes

2024-03-28 12:11 UTC, merged