update copy on pricing page
FlowFuse/website pull request #1846
Opened 2024-03-27 19:25 UTC by ZJvandeWeg

## Description

## Related Issue(s)

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

2024-03-27 21:21 UTC, Hasmin-AC approved these changes

2024-03-27 21:23 UTC, Hasmin-AC commented
now that there isn't too much text for contact us, @Yndira-E what do you think of making this a heading with the Form below it instead of on the side?

2024-03-28 08:56 UTC, Yndira-E commented
Hi @Hasmin-AC this can be part of the design review I'll be doing soon, pricing page will be the first one 😉. So feel free to merge as is and we'll handle that in a different PR.

2024-03-28 09:16 UTC, Yndira-E requested changes

2024-03-28 09:16 UTC, Yndira-E commented on src/pricing/index.njk
> +    setupPricingSlider("#enterprise-monthly-slider", 600, 5, "#enterprise-monthly-price-int", "#enterprise-monthly-price-dec", "#enterprise-monthly-price-note", "#enterprise-monthly-value", false);
I can see new minimum instances. There are other sections of the code that need to be updated as well, I'll update what's needed (maybe I'll iterate on the script instead)

2024-03-28 09:52 UTC, Yndira-E approved these changes

2024-03-28 09:52 UTC, Yndira-E commented on src/pricing/index.njk
> +    setupPricingSlider("#enterprise-monthly-slider", 600, 5, "#enterprise-monthly-price-int", "#enterprise-monthly-price-dec", "#enterprise-monthly-price-note", "#enterprise-monthly-value", false);
I already updated the script

2024-03-28 09:55 UTC, Yndira-E commented
Since I'm the last one approving, I'm merging it now.

2024-03-28 09:55 UTC, merged