Press release blog on GIS Partnership
FlowFuse/website pull request #1848
Opened 2024-03-27 22:01 UTC by Hasmin-AC

## Description

## Related Issue(s)

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

2024-03-27 22:02 UTC, Hasmin-AC commented on src/blog/2024/03/FlowFuse-Gallarus-Strategic-Partnership-to-Accelerate-Industry-4-Adoption
> +For more information about FlowFuse and Gallarus Industry Solutions Limited, please visit their respective websites at flowfuse.com and gis.ie.
```suggestion
For more information about FlowFuse and Gallarus Industry Solutions Limited, please visit their respective websites at [flowfuse.com](http://flowfuse.com) and [gis.ie.](http://gis.ie)
```

2024-03-27 22:03 UTC, Hasmin-AC commented
@Yndira-E can you please add that image you created for Press release to this blog post too. Thanks!

2024-03-28 09:40 UTC, Yndira-E commented
Hi @Hasmin-AC, this task is quite straightforward! Since you already have the image, I thought this could be a great learning opportunity for you. Would you mind giving it a try and adding it yourself?

For reference, you can check out some examples of how other articles are formatted. And just to help you along, you'll need to upload the file to this folder: https://github.com/FlowFuse/website/tree/GIS-Partnership-Blog/src/blog/2024/03/images 

Thank you for taking this on! 🌟

2024-03-28 14:40 UTC, Hasmin-AC commented on src/blog/2024/03/FlowFuse-Gallarus-Strategic-Partnership-to-Accelerate-Industry-4-Adoption
> +image:
```suggestion
image: /blog/2024/03/images/Flowfuse-Gallarus-Partnership.png
```

2024-03-28 14:51 UTC, Hasmin-AC commented on src/blog/2024/03/FlowFuse-Gallarus-Strategic-Partnership-to-Accelerate-Industry-4-Adoption
> +authors:
```suggestion
authors: ["-"]
```

2024-03-28 16:30 UTC, Yndira-E commented on src/blog/2024/03/FlowFuse-Gallarus-Strategic-Partnership-to-Accelerate-Industry-4-Adoption.md
> +    -
```suggestion
```

2024-03-28 17:11 UTC, Yndira-E requested changes
@Hasmin-AC the short description is way too long, you need to move the `<!--more-->` tag. Check the [handbook](https://flowfuse.com/handbook/customer/marketing/blog/).

<img width="898" alt="Screenshot 2024-03-28 at 18 08 42" src="https://github.com/FlowFuse/website/assets/129537638/9180c445-d2dd-4c3b-a4f6-9cdb5f017d4e">

2024-03-28 17:35 UTC, Yndira-E approved these changes

2024-03-28 17:35 UTC, merged