blog : Sending and receiving Telegram messages with Node-RED
FlowFuse/website pull request #1922
Opened 2024-04-11 14:31 UTC by sumitshinde-84

## Description

## Related Issue(s)

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

2024-04-12 13:36 UTC, gdziuba requested changes
In stead of bullet points can we do numbers instead since they are steps?

2024-04-12 13:36 UTC, gdziuba commented on src/blog/2024/04/sending-and-receiving-telegram-messages-with-node-red.md
> +!["screenshot displaying chat interface with start buttom for activating your bot"](./images/sending-telegram-with-node-red-activating-bot.png "screenshot displaying chat interface with start buttom
```suggestion
!["screenshot displaying chat interface with start button for activating your bot"](./images/sending-telegram-with-node-red-activating-bot.png "screenshot displaying chat interface with start button for activating your bot"){data-zoomable}
```

2024-04-12 13:36 UTC, gdziuba commented on src/blog/2024/04/sending-and-receiving-telegram-messages-with-node-red.md
> +!["Screenshot displaying flowfuse instance settings for adding enviroment varible"](./images/sending-telegram-with-node-red-flowfue-instance-settings.png "Screenshot displaying flowfuse instance sett
```suggestion
!["Screenshot displaying flowfuse instance settings for adding environment varible"](./images/sending-telegram-with-node-red-flowfue-instance-settings.png "Screenshot displaying flowfuse instance settings for adding environment variable"){data-zoomable}
```

2024-04-12 13:36 UTC, gdziuba commented on src/blog/2024/04/sending-and-receiving-telegram-messages-with-node-red.md
> +- Drag a Change node onto the canvas. Set msg.payload.type as "message"  To explore other types, refer to the [node readme](https://flows.nodered.org/node/node-red-contrib-telegrambot), set msg.paylo
```suggestion
- Drag a Change node onto the canvas. Set msg.payload.type as "message."  To explore other types, refer to the [node readme](https://flows.nodered.org/node/node-red-contrib-telegrambot), set msg.payload.chatId as the environment variable added for the chat ID, and then set msg.payload.content as the message you want to send.
```

2024-04-12 13:36 UTC, gdziuba commented on src/blog/2024/04/sending-and-receiving-telegram-messages-with-node-red.md
> +!["Screenshot displaying node-red flow for sending and receving telegram messages"](./images/sending-telegram-with-node-red-flow.png "Screenshot displaying node-red flow for sending and receving tele
```suggestion
!["Screenshot displaying node-red flow for sending and receiving telegram messages"](./images/sending-telegram-with-node-red-flow.png "Screenshot displaying node-red flow for sending and receiving telegram messages"){data-zoomable}
```

2024-04-12 13:36 UTC, gdziuba commented on src/blog/2024/04/sending-and-receiving-telegram-messages-with-node-red.md
> +- Switch to the "Install" tab
Missing a step or two.  Tell the reader to switch over to FlowFuse and log into your node-red instance or something like that.

2024-04-12 13:36 UTC, gdziuba commented on src/blog/2024/04/sending-and-receiving-telegram-messages-with-node-red.md
> +!["screenshot displaying searching "Get My ID" bot for obtaining chat id"](./images/sending-telegram-with-node-red-getmyid.png "screenshot displaying searching "Get My ID" bot for obtaining chat id")
```suggestion
!["screenshot displaying searching &quot;Get My ID&quot; bot for obtaining chat id"](./images/sending-telegram-with-node-red-getmyid.png "screenshot displaying searching &quot;Get My ID&quot; bot for obtaining chat id"){data-zoomable}
```

2024-04-12 13:43 UTC, sumitshinde-84 commented
> In stead of bullet points can we do numbers instead since they are steps?

Apologies for forgetting again. I'll make sure to use numbers instead of bullet points.

2024-04-12 13:51 UTC, gdziuba commented
> > In stead of bullet points can we do numbers instead since they are steps?
> 
> Apologies for forgetting again. I'll make sure to use numbers instead of bullet points.

I like the content.

2024-04-12 13:52 UTC, gdziuba commented on src/blog/2024/04/sending-and-receiving-telegram-messages-with-node-red.md
> +   - telegram
```suggestion
   - telegram
   - bot
```

2024-04-12 13:52 UTC, gdziuba commented on src/blog/2024/04/sending-and-receiving-telegram-messages-with-node-red.md
> +date: 2024-04-08
Need to adjust the date.

2024-04-12 20:22 UTC, gdziuba approved these changes

2024-04-12 20:22 UTC, gdziuba commented
It needs art tile, then it is good to go.

2024-04-15 14:22 UTC, ZJvandeWeg approved these changes

2024-04-15 14:27 UTC, merged