Add certified nodes process to handbook
FlowFuse/website pull request #2235
Opened 2024-06-21 15:04 UTC by knolleary

Not too heavy on details, but gets the basic information in place so team members searching the handbook will find something get get directed to the right place.

2024-06-21 17:22 UTC, joepavitt requested changes

2024-06-21 17:22 UTC, joepavitt commented on src/handbook/development/certified-nodes.md
> +instances withing FlowFuse.
```suggestion
instances within FlowFuse.
```

2024-06-21 17:22 UTC, joepavitt approved these changes

2024-06-21 17:22 UTC, joepavitt commented
Approved subject to minor typo

2024-06-24 11:57 UTC, knolleary commented
For future ref, if you spot a minor type, please feel free to self-merge the correction and approve the PR.

2024-06-24 11:57 UTC, merged