Blog: Using MySQL with Node-RED
FlowFuse/website pull request #2364
Opened 2024-07-18 14:03 UTC by sumitshinde-84

## Description

## Related Issue(s)

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

2024-07-30 16:00 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +
```suggestion
<!--more-->

```

2024-07-30 16:24 UTC, gdziuba requested changes

2024-07-30 16:24 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +When discussing popular and widely used databases, MySQL inevitably stands out. This is especially evident within the Node-RED community, where the MySQL contrib node has the highest number of downlo
```suggestion
When discussing popular and widely used databases, MySQL inevitably stands out. This is especially evident within the Node-RED community, where the MySQL contrib node has the highest number of downloads among all database contrib nodes. However, popularity often brings its own set of challenges. We've prepared this comprehensive guide to help our Node-RED community members navigate these challenges. It covers all aspects of using MySQL with Node-RED, including an overview of what MySQL is, the differences between PostgreSQL and MySQL, when to choose one over the other, essential MySQL operations, and more.
```

2024-07-30 16:24 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +[MySQL](https://dev.mysql.com/doc/) is an open-source relational database management system (RDBMS) developed by MySQL AB, which was later acquired by Sun Microsystems and then Oracle Corporation. It
```suggestion
[MySQL](https://dev.mysql.com/doc/) is an open-source relational database management system (RDBMS) developed by MySQL AB, which Sun Microsystems later acquired and then Oracle Corporation. It uses SQL (Structured Query Language) to query and manage databases. MySQL is widely recognized for its performance, scalability, and ease of use.
```

2024-07-30 16:24 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +## MySQL Vs PostgreSQL
```suggestion
## MySQL vs PostgreSQL 
```

2024-07-30 16:24 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +Deciding between [PostgreSQL](/node-red/database/postgresql/) and MySQL depends on what your project needs and what each database system does best. PostgreSQL is ideal for big projects that need comp
```suggestion
Deciding between [PostgreSQL](/node-red/database/postgresql/) and MySQL depends on your project's needs and what each database system does best. PostgreSQL is ideal for big projects requiring complex data handling, reliability, and often updated data. It works well in environments where keeping data consistent is crucial. PostgreSQL's advanced features, like materialized views and support for writing procedures in different languages beyond SQL make it great for managing sophisticated data needs.
```

2024-07-30 16:24 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +On the other hand, MySQL is excellent for projects that prioritize fast reading of data and are easy to set up and use. It's commonly used for smaller projects, quick prototypes, or applications wher
```suggestion
On the other hand, MySQL is excellent for projects that prioritize fast data reading and are easy to set up and use. It's commonly used for smaller projects, quick prototypes, or applications where quick deployment is critical. MySQL offers flexibility with different storage options—like InnoDB for transactions and MyISAM for handling lots of reads simultaneously—making it versatile depending on your workload.
```

2024-07-30 16:24 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +In this section of the article, we will cover how you can configure MySQL with Node-RED, create and delete tables, and perform essential operations such as inserting, retrieving, updating, and deleti
```suggestion
This section of the article will cover how to configure MySQL with Node-RED, create and delete tables, and perform essential operations such as inserting, retrieving, updating, and deleting data. These operations are crucial for any application.
```

2024-07-30 16:24 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +Additionally for the demonstration purpose article uses the simple weather data example so make sure you update the SQL queries according to your data and application needs. also through the article
```suggestion
Additionally, for the demonstration purpose, the article uses a simple weather data example, so make sure you update the SQL queries according to your data and application needs. Also, through the article, we have used the inject nodes for ease to set the example data and trigger, but instead, you could utilize the Node-RED Dashboard 2.0 to grab the data from the user and trigger it.
```

2024-07-30 16:24 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +- The MySQL custom node [node-red-contrib-mysql](https://flows.nodered.org/node/node-red-node-mysql) installed in your Node-RED environment.
```suggestion
- The MySQL custom node [node-red-contrib-mysql](https://flows.nodered.org/node/node-red-node-mysql) is installed in your Node-RED environment.
```

2024-07-30 16:24 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +2. Double Click on it, Click on the "+" button located next to the "Database" field.
```suggestion
2. Double-click on it, then Click on the "+" button located next to the "Database" field.
```

2024-07-30 16:24 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +2. Drag a Template node onto the canvas. Insert the following SQL into it. Note how the Template node dynamically inserts the value of `msg.payload` into the query. If you want to set the date and ti
```suggestion
2. Drag a Template node onto the canvas. Insert the following SQL into it. Note how the Template node dynamically inserts the value of `msg.payload` into the query. If you want to set the date and time using Node-RED, you can similarly set it up as you did for `msg.payload`, currently, we are using the MySQL function for setting time.
```

2024-07-30 16:24 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +1. Drag an Inject node onto the canvas, and set `msg.payload` to the data you want to update with.
```suggestion
1. Drag an Inject node onto the canvas and set the message.payload to the data you want to update
```

2024-07-30 16:24 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +2. Drag a Template node onto the canvas. Insert the following SQL into it. In this SQL query, we are setting the `id` statically which we are using to update the data, but you can also dynamically se
```suggestion
2. Drag a Template node onto the canvas. Insert the following SQL into it. In this SQL query, we are setting the `id` statically, which we are using to update the data, but you can also dynamically set it just like we did for `tem`. We have utilized the `WHERE` clause here, but there are plenty of other SQL clauses available for more complex operations. For more information Refer to this blog on [SQL Clauses (https://www.educba.com/sql-clauses/)
```

2024-07-30 16:24 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +1. To test the imported flows, you need to deploy them. To do that, click on the deploy button located in the top right corner.
```suggestion
1. To test the imported flows, you need to deploy them. To do that, click the deploy button at the top right corner.
```

2024-07-30 16:24 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +After deploying the flow, you can test each operation—such as creating, deleting, updating, and executing other queries—by clicking the inject button. For debugging purposes, you can add debug nodes
```suggestion
After deploying the flow, you can test each operation—such as creating, deleting, updating, and executing other queries—by clicking the inject button. For debugging purposes, add debug nodes to the flow. 
```

2024-07-30 16:24 UTC, gdziuba commented on src/blog/2024/07/using-mysql-with-node-red.md
> +In summary, this guide has equipped you with essential skills for integrating MySQL with Node-RED. You've learned how to set up and manage MySQL nodes, perform crucial database operations, and levera
```suggestion
This guide has equipped you with essential skills for integrating MySQL with Node-RED. You've learned how to set up and manage MySQL nodes, perform crucial database operations, and leverage MySQL's capabilities within Node-RED for efficient data handling and automation.
```

2024-07-31 17:19 UTC, sumitshinde-84 commented
Hi @gdziuba I have applied all of the suggestion, could you please re-review it ?

2024-08-01 13:03 UTC, gdziuba commented on src/blog/2024/08/using-mysql-with-node-red.md
> +2. Drag a Template node onto the canvas. Insert the following SQL into it. In this SQL query, we are setting the `id` statically, which we are using to update the data, but you can also dynamically s
```suggestion
2. Drag a Template node onto the canvas. Insert the following SQL into it. In this SQL query, we are setting the `id` statically, which we are using to update the data, but you can also dynamically set it just like we did for `tem`. We have utilized the `WHERE` clause here, but there are plenty of other SQL clauses available for more complex operations. For more information, refer to this blog on [SQL Clauses (https://www.educba.com/sql-clauses/)
```

2024-08-01 13:04 UTC, gdziuba approved these changes

2024-08-01 13:07 UTC, gdziuba commented
Can't merge because of local install links.   I think @joepavitt is working on this.

2024-08-01 13:08 UTC, joepavitt commented
Yep, ignore the test failures, they're being fixed elsewhere

2024-08-01 14:23 UTC, merged