Update redirect.md
FlowFuse/website pull request #2532
Opened 2024-09-03 14:20 UTC by sumitshinde-84

## Description

## Related Issue(s)

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

2024-09-03 14:21 UTC, ZJvandeWeg requested changes

2024-09-03 14:21 UTC, ZJvandeWeg commented on src/redirect.md
> +  - { "from": "/node-red/core-nodes/watch/", "to": "/node-red/core-nodes/read-filee/" }
Typo.

2024-09-03 15:35 UTC, sumitshinde-84 commented on src/redirect.md
> +  - { "from": "/node-red/core-nodes/watch/", "to": "/node-red/core-nodes/read-file/" }
We have updated the `watch -> read-file`

2024-09-04 07:33 UTC, ZJvandeWeg approved these changes

2024-09-04 07:33 UTC, merged