Update customer-success.md
FlowFuse/website pull request #2673
Opened 2024-10-15 15:15 UTC by MichaelBDavis

Update churn playbook

## Description

## Related Issue(s)

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

2024-10-16 09:11 UTC, ZJvandeWeg requested changes

2024-10-16 13:11 UTC, MichaelBDavis commented on src/handbook/customer/customer-success.md
> +   Access the Contracted Customer Tracker and move the churned customer to the "Churned" tab.
Yes, do i click "start a review" to make this change?

2024-10-17 08:30 UTC, ZJvandeWeg commented on src/handbook/customer/customer-success.md
> +   Access the Contracted Customer Tracker and move the churned customer to the "Churned" tab.
<img width="379" alt="Screenshot 2024-10-17 at 10 29 54" src="https://github.com/user-attachments/assets/574207fc-6e18-4276-9c0b-44a1cdbee7c0">
If you click that and update the text to what it should do, you can coment that and accept your own suggestion. Links in markdown are written as: `[Link text](https://your.location.tld/)`

2024-10-17 18:22 UTC, MichaelBDavis commented on src/handbook/customer/customer-success.md
> +   Access the Contracted Customer Tracker and move the churned customer to the "Churned" tab.
Access the [Contracted Customer Tracker](https://docs.google.com/spreadsheets/d/1QcGVeiO_RXwYHCZvGcuBW3oYgR5NMsQ22yi3cOFY73o/edit?gid=1852075496#gid=1852075496) and move the churned customer to the "Churned" tab.

2024-10-18 07:33 UTC, ZJvandeWeg commented on src/handbook/customer/customer-success.md
> +   Access the Contracted Customer Tracker and move the churned customer to the "Churned" tab.
```suggestion
   Access the [Contracted Customer Tracker](https://docs.google.com/spreadsheets/d/1QcGVeiO_RXwYHCZvGcuBW3oYgR5NMsQ22yi3cOFY73o/edit?gid=1852075496#gid=1852075496) and move the churned customer to the "Churned" tab.
```

2024-10-18 07:34 UTC, ZJvandeWeg approved these changes

2024-10-18 07:34 UTC, merged