Blog: MQTT: The Frontrunner for Your UNS Broker
FlowFuse/website pull request #2687
Opened 2024-10-21 11:21 UTC by sumitshinde-84

## Description

## Related Issue(s)

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

2024-10-22 14:48 UTC, ZJvandeWeg commented on src/blog/2024/10/images/mqtt-compatiblity.png
Sensors only publish data?

2024-10-22 14:58 UTC, sumitshinde-84 commented on src/blog/2024/10/images/mqtt-compatiblity.png
I haven't found any other image. How about using the one we are planning to use on the MQTT page?

2024-10-30 07:51 UTC, ZJvandeWeg requested changes

2024-10-30 07:51 UTC, ZJvandeWeg commented on src/blog/2024/10/mqtt-frontrunner-for-uns.md
> +Is MQTT truly the go-to option for your UNS broker, or are there better alternatives out there? As the IoT landscape evolves, it's worth questioning whether its lightweight design can meet the demand
Second sentence is to chatgpt for me.

2024-10-30 07:51 UTC, ZJvandeWeg commented on src/blog/2024/10/mqtt-frontrunner-for-uns.md
> +The [Unified Namespace (UNS)](/blog/2023/12/introduction-to-unified-namespace/) (UNS) is a popular way to organize data from all components of your IoT environment in a centralized place, making it e
Is it IIoT in this case? User authorization isn't part of UNS, and the communication is mostly machine to machine?

2024-10-30 07:51 UTC, ZJvandeWeg commented on src/blog/2024/10/mqtt-frontrunner-for-uns.md
> +Why do you need a protocol in the UNS? A robust communication protocol ensures seamless interactions among diverse devices and systems. It establishes standardized methods for data exchange, which he
```suggestion
Why do you need a communication protocol in the UNS? A robust communication protocol ensures seamless interactions among diverse devices and systems. It establishes standardized methods for data exchange, which helps maintain data integrity, enhances interoperability, and enables scalability across various applications.
```

Again too chatGPT, please rewrite I'm full to explain the need for a broker without playing buzzword bingo.

2025-01-06 13:53 UTC, ZJvandeWeg requested changes

2025-01-06 13:53 UTC, ZJvandeWeg commented on src/blog/2025/01/mqtt-frontrunner-for-uns.md
> +[MQTT](/node-red/protocol/mqtt/) was developed in the late 1990s by **Andy Stanford-Clark** at **IBM** and **Arlen Nipper** at **Eurotech** to address communication challenges in low-bandwidth, unrel
```suggestion
[MQTT](/node-red/protocol/mqtt/) was developed in the late 1990s by Andy Stanford-Clark at IBM and Arlen Nipper at Eurotech to address communication challenges in low-bandwidth, unreliable networks. This early focus on lightweight messaging paved the way for MQTT to become a pioneering solution for the rapidly expanding IoT space.
```

2025-01-06 13:53 UTC, ZJvandeWeg commented on src/blog/2025/01/mqtt-frontrunner-for-uns.md
> +When choosing a broker for your UNS, it's crucial to consider how well the selected broker fits the specific requirements of your IIoT environment, including the types of devices and systems involved
```suggestion
When choosing a broker for your UNS, it's crucial to consider how well the selected broker fits the specific requirements of your IIoT environment, including the types of devices and systems involved, as well as factors like scalability, reliability, and ease of integration. Several options are available alongside MQTT, including [AMQP](/node-red/protocol/amqp/), [Kafka](/blog/2024/03/using-kafka-with-node-red/), and cloud message brokers like AWS Kinesis and GCP Pub/Sub. While these alternatives offer unique features, MQTT stands out, and we’ll explain why later in this article. But If you’re interested in a brief overview of why these alternatives are not the best fit for UNS, check out our article: [Unified Namespace: What Broker to Use?](/blog/2024/01/unified-namespace-what-broker/)
```

2025-01-06 13:53 UTC, ZJvandeWeg commented on src/blog/2025/01/mqtt-frontrunner-for-uns.md
> +Downtime in industrial operations can be very costly—ranging from $15,000 to $20,000 per minute or more. For engineers and operators watching over machines, waiting for data can mean the difference b
Do we have a linkable source for the owntime costs?

2025-01-06 13:53 UTC, ZJvandeWeg commented on src/blog/2025/01/mqtt-frontrunner-for-uns.md
> +This is where **MQTT** truly shines. It’s built with a **Quality of Service (QoS)** mechanism that allows you to control how reliably your messages are delivered. Depending on the level you choose, y
```suggestion
This is where MQTT truly shines. It’s built with a **Quality of Service (QoS)** mechanism that allows you to control how reliably your messages are delivered. Depending on the level you choose, you can ensure that data is delivered exactly as you need it, without compromising on system performance.
```

2025-01-06 13:53 UTC, ZJvandeWeg commented on src/blog/2025/01/mqtt-frontrunner-for-uns.md
> +Now, some other protocols like **AMQP** or **Kafka** also provide reliability guarantees, but they tend to be more complex and come with heavier infrastructure requirements. MQTT, on the other hand,
Can we not use bold so often?

2025-01-07 14:05 UTC, ZJvandeWeg approved these changes

2025-01-07 14:05 UTC, merged