MQTT: The Frontrunner for Your UNS Broker - Part 2
FlowFuse/website pull request #2724
Opened 2024-10-30 04:48 UTC by sumitshinde-84

## Description

## Related Issue(s)

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

2024-11-23 09:25 UTC, ZJvandeWeg commented
@sumitshinde-84 I don't think this is ready for review yet?

2025-01-08 08:22 UTC, ZJvandeWeg requested changes

2025-01-08 08:22 UTC, ZJvandeWeg commented on src/blog/2025/01/mqtt-frontrunner-for-uns-part-2.md
> +In Part 1 , we discussed the compelling reasons behind MQTT's popularity as a choice for Unified Namespace (UNS) implementations, focusing on its lightweight design, low latency, and reliable message
let's link to part 1.

2025-01-08 08:22 UTC, ZJvandeWeg commented on src/blog/2025/01/mqtt-frontrunner-for-uns-part-2.md
> +## **Wide Connectivity**
@Yndira-E Sumit often uses bold in the headers like this. Is this something we should do with CSS instead?

2025-01-08 08:22 UTC, ZJvandeWeg commented on src/blog/2025/01/mqtt-frontrunner-for-uns-part-2.md
> +For your Unified Namespace (UNS) to function properly, it needs to collect data from a variety of devices and systems. MQTT is perfect for this because it can connect to a wide range of devices, from
```suggestion
For your UNS to be valuable it needs to transport data from a variety of devices and systems. MQTT is perfect for this because it can connect to a wide range of devices, from modern systems to older legacy equipment.
```

2025-01-08 08:22 UTC, ZJvandeWeg commented on src/blog/2025/01/mqtt-frontrunner-for-uns-part-2.md
> +One of the biggest advantages of MQTT is its broad compatibility. It works seamlessly in cloud-based systems and is widely supported in industrial environments. This makes MQTT a natural fit for conn
I don't think this is true, old machines don't really support MQTT natively -- which is where Node-RED comes in. You also note this in the next line. As such, I think we should not have 1 line paragraphs like this and have more deep thought on what you want to say in this paragraph.

2025-01-08 09:48 UTC, Yndira-E commented on src/blog/2025/01/mqtt-frontrunner-for-uns-part-2.md
> +## **Wide Connectivity**
I set up the CSS for headers when we rebranded the website, so there shouldn’t be a need to adjust it further. I guess Sumit feels the styling isn’t strong enough by default. I can increase the weight slightly but not make it bold, as we aim to avoid using weights heavier than semi-bold. [Here’s the handbook section](https://flowfuse.com/handbook/design/branding/#fonts) that outlines our approach to fonts.

2025-01-08 10:10 UTC, ZJvandeWeg commented on src/blog/2025/01/mqtt-frontrunner-for-uns-part-2.md
> +## **Wide Connectivity**
@sumitshinde-84 ^

Can you create a new PR if we applied bold to titles earlier and remove it?

2025-01-08 10:12 UTC, Yndira-E commented on src/blog/2025/01/mqtt-frontrunner-for-uns-part-2.md
> +## **Wide Connectivity**
I’ve just checked, and the current styling is consistent with the headers across the website. To maintain this consistency, my recommendation would be to avoid adding any extra styling to the headers, as this is already handled by the CSS.

2025-01-08 10:36 UTC, sumitshinde-84 commented on src/blog/2025/01/mqtt-frontrunner-for-uns-part-2.md
> +## **Wide Connectivity**
I will create separate PR to remove all bold headers now

2025-01-12 07:59 UTC, ZJvandeWeg approved these changes

2025-01-12 07:59 UTC, ZJvandeWeg commented on src/blog/2025/01/mqtt-frontrunner-for-uns-part-2.md
> +In [Part 1](/blog/2025/01/mqtt-frontrunner-for-uns/), we discussed the compelling reasons behind MQTT's popularity as a choice for Unified Namespace (UNS) implementations, focusing on its lightweight
```suggestion
In [Part 1](/blog/2025/01/mqtt-frontrunner-for-uns/), we discussed the  reasons behind MQTT's popularity as a choice for Unified Namespace (UNS) implementations; focusing on its lightweight design, low latency, and reliable message delivery. In this second part, we’ll explore additional factors that further establish MQTT as the leading protocol for UNS brokers, diving into its connectivity, scalability, structured topic management. 
```

2025-01-12 07:59 UTC, ZJvandeWeg commented on src/blog/2025/01/mqtt-frontrunner-for-uns-part-2.md
> +In a factory, you typically have a mix of physical devices (like sensors and machines) and cloud systems. To make real-time decisions, data needs to flow seamlessly from the shop floor to the cloud.
```suggestion
In a typical industrial data architecture, you typically have a mix of physical devices (like sensors and machines) and cloud systems. To make real-time decisions, data needs to flow seamlessly from the shop floor to the cloud. MQTT excels at connecting modern devices with the cloud. However, one challenge is that it doesn’t natively support older systems that typically use protocols like OPC UA or MODBUS.
```

2025-01-13 10:49 UTC, merged