Blog: Bridging Modbus Data to MQTT using Node-RED
FlowFuse/website pull request #2788
Opened 2024-11-19 14:50 UTC by sumitshinde-84

## Description

## Related Issue(s)

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

2024-11-20 20:47 UTC, Hasmin-AC commented on src/blog/2024/11/bridging-modbus-to-mqtt.md
> +description: Learn how to bridge Modbus data to MQTT using Node-RED for cloud integration and real-time industrial monitoring.
Need to mention FlowFuse

2024-11-20 20:47 UTC, Hasmin-AC commented on src/blog/2024/11/bridging-modbus-to-mqtt.md
> +Modbus is a popular protocol in industrial automation used to connect devices like sensors and PLCs, but it’s not designed to connect easily with cloud platforms or modern IoT systems. MQTT, however,
```suggestion
Modbus is a popular protocol in industrial automation used to connect devices like sensors and PLCs, but it’s not designed to connect easily with cloud platforms or modern IoT systems. MQTT, however, is well-suited for real-time data transfer to the cloud. Using Node-Red, you can bridge the gap between Modbus and MQTT, allowing older equipment to connect to modern IoT networks. Let’s take a look at how you can set this up on the FlowFuse Platform. 
```

2024-11-20 20:47 UTC, Hasmin-AC commented on src/blog/2024/11/bridging-modbus-to-mqtt.md
> +
There's no mention of FlowFuse at all in this conclusion. I would suggest editing this part accordingly.

2024-11-21 07:58 UTC, ZJvandeWeg commented on src/blog/2024/11/bridging-modbus-to-mqtt.md
> +title: Bridging Modbus Data to MQTT using FlowFuse
Alternatively we could make this UNS focussed, what do you think? `Publishing Modbus data to your UNS with FlowFuse`?

2024-11-21 07:58 UTC, ZJvandeWeg commented on src/blog/2024/11/bridging-modbus-to-mqtt.md
> +title: Bridging Modbus Data to MQTT using FlowFuse
let's also consider updating the filename and thus the blog URL path

2024-11-23 09:24 UTC, ZJvandeWeg commented
@sumitshinde-84 Still some unresolved notes, is this ready for review?

2024-11-25 17:47 UTC, Hasmin-AC approved these changes

2024-11-25 17:47 UTC, Hasmin-AC commented on src/blog/2024/11/publishing-modbus-data-to-uns.md
> +This section will cover the steps to bridge Modbus data to MQTT using FlowFuse, leveraging Node-RED's capabilities. The process involves retrieving data from a Modbus device (For Practical example, w
```suggestion
Let's look at the steps to bridge Modbus data to MQTT using FlowFuse, leveraging Node-RED's capabilities. The process involves retrieving data from a Modbus device (For Practical example, we are using OpenSim to simulate Modbus data), transforming and processing the data (e.g., scaling raw sensor data into human-readable formats), and sending it to your Unified Namespace.
```

2024-11-26 08:25 UTC, ZJvandeWeg commented on src/blog/2024/11/images/mqtt-client-explorer.png
Can we use the FF topic browser?

2024-11-26 09:07 UTC, ZJvandeWeg requested changes

2024-12-02 08:14 UTC, ZJvandeWeg requested changes

2024-12-02 08:14 UTC, ZJvandeWeg commented on src/blog/2024/11/publishing-modbus-data-to-uns.md
> +While Modbus excels in local control and data collection, it struggles to integrate with cloud-based platforms and real-time IoT solutions. That's where MQTT, a lightweight, real-time messaging proto
This paragraph needs to be about UNS, not MQTT. MQTT is a broker _choice_ for the UNS which is the data architecture to communicate with arbitrary consumers. For our UNS we use MQTT, which then links to your other post about setting up a UNS in 15 minutes?

2024-12-03 21:05 UTC, Hasmin-AC approved these changes

2024-12-04 11:08 UTC, ZJvandeWeg commented on src/blog/2024/12/publishing-modbus-data-to-uns.md
> +date: 2024-12-03
```suggestion
date: 2024-12-04
```

2024-12-04 11:09 UTC, ZJvandeWeg approved these changes

2024-12-04 11:09 UTC, merged